import type { WorldId } from '../../store/useWorldStore'

export const QUOTES: Record<WorldId, string[]> = {
  'silent-void': [
    'In the absence of sound, form becomes pure.',
    'Nothing moves, yet everything arrives.',
    'Silence is not empty. It is full of waiting.',
    'The void does not ask. It simply holds.',
    'Distance is only a measurement of forgetting.',
    'Here, time folds into stillness.',
    'What remains when light refuses to enter?',
    'The quietest spaces carry the heaviest memory.',
    'Emptiness is a kind of architecture.',
    'We meet only in the places we cannot name.',
    'No edge. No center. Only presence.',
    'The dark does not consume. It preserves.',
    'Breath becomes geometry.',
    'Absence is the most honest material.',
    'Between two thoughts, the universe rests.',
    'Stillness is motion too slow to perceive.',
    'The void remembers what language forgets.',
    'Here, every surface is a horizon.',
    'Nothing ends. It only becomes quieter.',
    'The deepest black is made of countless lights that chose not to shine.',
    'Form dissolves into intention.',
    'Silence is the original luxury.',
    'We are the distance between two silences.',
    'In perfect dark, the mind becomes the only landscape.',
    'What is left when desire has nowhere to land?',
    'The void is patient. It outlives every name.',
    'Stillness is not the opposite of motion. It is its source.',
    'Here, even memory moves slowly.',
    'The absence of color is a color of its own.',
    'Everything that matters arrives without sound.',
    'The quiet holds more than the noise can carry.',
    'In the void, every word becomes an object.',
    'We enter the dark to remember how to see.',
    'Nothing is missing. Everything is waiting.',
    'The most precise architecture is empty space.',
    'Silence does not hide. It reveals.',
    'Between the stars, the same quiet lives.',
    'The void is not a place. It is a condition.',
    'Time softens until it disappears.',
    'Here, the only direction is inward.',
    'Darkness is the canvas that never refuses.',
    'What cannot be spoken still occupies space.',
    'The quietest objects are the heaviest.',
    'In silence, structure becomes visible.',
    'We are temporary arrangements of stillness.',
    'The void does not judge. It simply continues.',
    'Absence has perfect proportions.',
    'Nothing needs to arrive. It is already here.',
    'The dark is the first and last material.',
    'In the end, only the quiet remains accurate.',
  ],

  // Placeholders for other worlds (will be expanded later)
  'blood-ritual': [
    'Crimson is the color of what cannot be returned.',
    'Ritual begins where language ends.',
    'The deepest red is made of memory and heat.',
  ],
  'editorial-studio': [
    'Form is the only statement that needs no explanation.',
    'White is never empty. It is waiting for decision.',
  ],
  'cosmic-infinity': [
    'Distance is the only true luxury of the universe.',
    'Every star is a forgotten intention.',
  ],
  'inferno-hearth': [
    'Warmth is the last honest language.',
    'Fire does not destroy. It clarifies.',
  ],
  'cyberpunk-district': [
    'The future is already leaking through the cracks.',
    'Neon is the new blood.',
  ],
  'matrix-rain': [
    'Code is the only prayer that still works.',
    'The rain never stops. Only the observer does.',
  ],
  'ocean-depths': [
    'Pressure is a form of tenderness.',
    'The deep does not speak. It listens.',
  ],
  'glass-dimension': [
    'Transparency is the most expensive opacity.',
    'Reflection is the original mirror.',
  ],
  'aurora-sky': [
    'Light that moves without source is the purest.',
    'The sky remembers every color it has ever been.',
  ],
}
